; The Online Subsystem to be used by the engine.
[OnlineSubsystem]
DefaultPlatformService=Steam

; Specific configuration of the Steam Online Subsystem.
[OnlineSubsystemSteam]
bEnabled=True
SteamDevAppId=480
GameServerQueryPort=27015
bInitServerOnClient=False
bAllowP2PPacketRelay=True
P2PConnectionTimeout=90
bRelaunchInSteam=False
bVACEnabled=False

; The net drivers to be used by the game.
; GameNetDriver: Used by regular game connections (server-client).
; BeaconNetDriver: Used by the party and reservation systems of Nexus.
[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
;+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
;+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/SteamSockets.SteamSocketsNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/SteamSockets.SteamSocketsNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")

; The net drivers to be used by the editor.
; Only ever used during PIE so just use the IpNetDriver.
[/Script/UnrealEd.EditorEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")

; Specific configuration of the Steam Net Driver.
[/Script/SteamSockets.SteamSocketsNetDriver]
ConnectionTimeout=60.0
InitialConnectTimeout=120.0
NetConnectionClassName="SteamSockets.SteamSocketsNetConnection"